local lib = {}

lib.Widget = require("./Immco/components/Widget")
lib.Rectangle = require("./Immco/components/Rectangle")
lib.Text = require("./Immco/components/Text")
lib.Image = require("./Immco/components/Image")
lib.RoundedRectangle = require("./Immco/components/RoundedRectangle")
lib.TextButton = require("./Immco/components/TextButton")
lib.ImageButton = require("./Immco/components/ImageButton")
lib.Checkbox = require("./Immco/components/Checkbox")
lib.TextInput = require("./Immco/components/TextInput")

return lib
